# Generated by Django 5.2 on 2025-04-03 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True

    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("account_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                ("bank_code", models.CharField(choices=[
                    ("000", "알수없음"),
                    ("001", "한국은행"),
                    ("002", "산업은행"),
                    ("003", "기업은행"),
                    ("004", "국민은행"),
                    ("005", "외환은행"),
                    ("007", "수협중앙회"),
                    ("008", "수출입은행"),
                    ("011", "농협은행"),
                    ("012", "지역농.축협"),
                    ("020", "우리은행"),
                    ("023", "SC은행"),
                    ("027", "한국씨티은행"),
                    ("031", "대구은행"),
                    ("032", "부산은행"),
                    ("034", "광주은행"),
                    ("035", "제주은행"),
                    ("037", "전북은행"),
                    ("039", "경남은행"),
                    ("081", "KEB하나은행"),
                    ("088", "신한은행"),
                    ("089", "케이뱅크"),
                    ("090", "카카오뱅크"),
                    ("092", "토스뱅크"),
                ], max_length=20)),
                ("account_type", models.CharField(choices=[
                    ("CHECKING", "입출금"),
                    ("SAVING", "적금"),
                    ("LOAN", "대출"),
                    ("PENSION", "연금"),
                    ("TRUST", "신탁"),
                    ("FOREIGN_CURRENCY", "외화"),
                    ("IRP", "퇴직연금"),
                    ("STOCK", "주식")
                ], max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),

            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction_History",
            fields=[
                ("transaction_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transaction_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=20)),
                ("transaction_type", models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], max_length=20)),
                ("transaction_method", models.CharField(choices=[
                    ("ATM", "ATM 거래"),
                    ("TRANSFER", "계좌이체"),
                    ("AUTOMATIC_TRANSFER", "자동이체"),
                    ("CARD", "카드결제"),
                    ("INTEREST", "이자")
                ], max_length=20)),
                ("transaction_details", models.CharField(max_length=100)),
                ("transaction_timestamp", models.DateTimeField(auto_now_add=True)),
                ("account_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.Accounts")),

            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역 목록",
                "ordering": ["-transaction_timestamp"],
            },
        ),
    ]